FROM ruby:3.4.9

# gem pgのインストールでエラーを出さないように
RUN apt-get update && \
    apt-get install -y \
      build-essential \
      libpq-dev \
      postgresql-client && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY Gemfile Gemfile.lock ./

RUN bundle install

COPY . .

CMD ["rails", "server", "-b", "0.0.0.0"]